Repository DSC-University-of-Seoul/2021-spring-project, pull requests merged in 2021-08, with the labels that each got.

#112 #KDSK-112 ERD 최신화
  server/database/schema/ERD(v2.0.6).png
  server/database/schema/db_schema.md
Labels: Priority ❕ Low, PR 🙇‍♂️ REVIEW REQUEST, Extra 🏃 SIMPLE

#111 #KDSK-111 Humanpose와 Scheduler연계 I
  hub/config.yml.sample
  hub/core.py
  hub/main.py
  hub/process.py
  hub/requirements.txt
  hub/utils/config.py
  hub/utils/files.py
  hub/utils/general.py
  hub/utils/scheduler.py
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type 🛠 FEATURE

#103 #KDSK-106 로그 데이터 레이블링 별 집계
  .github/workflows/lint-action-js-BE.yml
  .github/workflows/lint-action-js-DB.yml
  .gitignore
  server/backend/.eslintrc.json
  server/backend/app.js
  server/backend/controllers/district.js
  server/backend/repositories/district.js
  server/backend/routes/api/anomaly.js
  server/backend/routes/api/cctv.js
  server/backend/routes/api/childCareCenter.js
  server/backend/routes/api/district.js
  server/backend/routes/api/index.js
  server/backend/routes/api/log.js
  server/backend/routes/district.js
  server/backend/routes/index.js
  server/backend/services/district.js
  server/package-lock.json
  server/package.json
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type 🛠 FEATURE

#109 #KDSK-110 데이터 타입 변경
  server/database/.eslintrc.js
  server/database/app.js
  server/database/config/config.js
  server/database/data_parsers/childCareCenterParser.js
  server/database/data_parsers/districtParser.js
  server/database/data_parsers/jejuChildCareCenterParser.js
  server/database/data_parsers/sejongChildCareCenterParser.js
  server/database/index.js
  server/database/models/anomaly.js
  server/database/models/cctv.js
  server/database/models/childCareCenter.js
  server/database/models/district.js
  server/database/models/index.js
  server/database/models/log.js
  server/database/models/member.js
  server/database/models/transform/anomaly.js
  server/database/models/transform/cctv.js
  server/database/models/transform/childCareCenter.js
  server/database/models/transform/district.js
  server/database/models/transform/index.js
  server/database/models/transform/log.js
  server/database/models/transform/member.js
  server/database/models/transform/video.js
  server/database/models/video.js
  server/database/package-lock.json
  server/database/package.json
  server/database/seeders/20210716132608-cctv.js
  server/database/seeders/20210716142704-anomaly.js
  server/database/seeders/20210716142843-member.js
  server/database/seeders/20210716142948-video.js
  server/database/seeders/20210716143008-log.js
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type 🕷 BUG FIX

#114 /utils 디렉토리의 파일 구조 변경
  app/src/components/MapBox.js
  app/src/containers/ChartContainer.js
  app/src/containers/MapBoxSelectContainer.js
  app/src/modules/cctvs.js
  app/src/modules/login.js
  app/src/modules/logs.js
  app/src/pages/Logs.js
  app/src/utils/axisName.js
  app/src/utils/cookie.js
  app/src/utils/districtViewport.js
  app/src/utils/format.js
  app/src/utils/mapStyle.js
Labels: Priority ❕ Low, Extra 🏃 SIMPLE, Type 🛠 FEATURE

#116 #KDSK-114 Hub refactoring
  hub/__init__.py
  hub/clients/__init__.py
  hub/clients/client.py
  hub/config.yml.sample
  hub/core.py
  hub/kidskeeper/__init__.py
  hub/process.py
  hub/requirements.txt
  hub/tests/test_proto.py
  hub/utils/__init__.py
  hub/utils/api.py
  hub/utils/config.py
  hub/utils/dump.py
  hub/utils/files.py
  hub/utils/logger.py
  hub/utils/scheduler.py
  hub/utils/updater.py
Labels: Priority ❕ Low, PR 🙇‍♂️ REVIEW REQUEST, Extra 🏃 SIMPLE, Type ⚙️ MAINTENANCE

#115 #KDSK-113 cctv_mac seed data 형식 수정
  server/database/schema/ERD(v2.0.6).png
  server/database/seeders/20210716132608-cctv.js
  server/database/seeders/20210716142704-anomaly.js
  server/database/seeders/20210716142948-video.js
  server/database/seeders/20210716143008-log.js
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Extra 🏃 SIMPLE, Type ⚙️ MAINTENANCE

#118 #KDSK-115 홈페이지 Favicon 추가
  app/public/favicon.ico
  app/public/index.html
  app/public/manifest.json
  app/webpack.config.js
Labels: Priority ❕ Low, Extra 🏃 SIMPLE, Type 🛠 FEATURE

#126 #KDSK-123 login 기능 구현
  .gitignore
  server/backend/app.js
  server/backend/middlewares/localLogin.js
  server/backend/package-lock.json
  server/backend/package.json
  server/backend/passports/index.js
  server/backend/passports/jwtStrategy.js
  server/backend/passports/localStrategy.js
  server/backend/repositories/district.js
  server/backend/routes/api/anomaly.js
  server/backend/routes/api/auth.js
  server/backend/routes/api/index.js
  server/backend/swagger/_openapi.yaml
  server/backend/swagger/build.yaml
  server/backend/swagger/paths/auth/login.yaml
  server/backend/swagger/paths/auth/member-update.yaml
  server/backend/swagger/paths/auth/register.yaml
  server/backend/swagger/paths/index.yaml
  server/database/models/member.js
  server/database/models/transform/log.js
  server/database/models/transform/member.js
  server/database/models/transform/video.js
  server/database/models/video.js
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type 🛠 FEATURE

#130 #KDSK-none rename branch
  app/src/components/UpdateLoginForm.js
  app/src/modules/login.js
  app/src/pages/Home.js
Labels: Priority ❔ Lowest, Extra 🏃 SIMPLE

#129 #KDSK-126 데이터 명세 최신화
  server/database/schema/ERD(v2.0.7).png
  server/database/schema/db_schema.md
  server/database/schema/db_schema_log.md
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Extra 🏃 SIMPLE, Type 📝DOCUMENT

#121 #KDSK-117 신규 로그에 대한 알림 기능 구성
  app/src/assets/sound/alarm.mp3
  app/src/components/Header.js
  app/src/components/ToggleBtn.js
  app/src/hooks/useLocalStorage.js
  app/src/modules/index.js
  app/src/modules/logs.js
  app/src/modules/settings.js
  app/src/pages/Settings.js
  app/src/styles/components/_header.scss
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type 🛠 FEATURE

#127 #KDSK-125 Hub 리팩토링 II
  hub/clients/aws.py
  hub/clients/client.py
  hub/clients/hub.py
  hub/core.py
  hub/utils/api.py
  hub/utils/config.py
  hub/utils/scheduler.py
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type ⚙️ MAINTENANCE

#131 #KDSK-127 모니터링 지도 기능 보완
  app/src/components/MapBox.js
  app/src/components/MapBoxCategory.js
  app/src/containers/MapBoxSelectContainer.js
  app/src/modules/mapbox.js
  app/src/modules/mapboxEvent.js
  app/src/styles/components/_mapbox.scss
  app/src/styles/components/_mapboxCategory.scss
  app/src/styles/components/_modal.scss
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type 🛠 FEATURE

#134 update refactoring
  hub/clients/aws.py
  hub/core.py
  hub/utils/time.py
Labels: Extra 🏃 SIMPLE

#124 #KDSK-121 제주시 seeder 삽입 후 연결 확인
  server/database/data_parsers/cctvs.js
  server/database/models/member.js
  server/database/package-lock.json
  server/database/package.json
  server/database/seeders/20210716132608-cctv.js
  server/database/seeders/20210716142704-anomaly.js
  server/database/seeders/20210716142843-member.js
  server/database/seeders/20210716142948-video.js
  server/database/seeders/20210716143008-log.js
  server/database/seeders/20210812093331-jeju-cctv.js
  server/database/seeders/20210812095156-jeju-video.js
  server/database/seeders/20210812095656-jeju-anomaly.js
  server/database/seeders/20210812095712-jeju-log.js
  server/database/seeders/20210819165823-1000cctvs.js
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Type 🛠 FEATURE

#137 #KDSK-129 페이지네이션 API 데이터 연계 구성
  app/src/components/Header.js
  app/src/components/Table.js
  app/src/components/TablePagination.js
  app/src/containers/CctvModalContainer.js
  app/src/containers/CctvTableContainer.js
  app/src/containers/LogTableContainer.js
  app/src/hooks/useOrderArray.js
  app/src/modules/allLogs.js
  app/src/modules/cctvs.js
  app/src/modules/index.js
  app/src/modules/logs.js
  app/src/modules/recentLogs.js
  app/src/modules/searchCenterModal.js
  app/src/pages/Cctvs.js
  app/src/pages/Home.js
  app/src/pages/Logs.js
Labels: Priority ‼️ High, Type 🛠 FEATURE, Extra ♎️ SUB BRANCH

#128 #KDSK-118 기능 및 백엔드 연계 간 발생하는 에러 확인 및 수정
  app/package.json
  app/src/components/BarChart.js
  app/src/components/UpdateLoginForm.js
  app/src/modules/login.js
  app/src/modules/mapboxEvent.js
  app/src/pages/Home.js
  app/src/styles/pages/_cctvs.scss
  app/webpack.config.js
  app/yarn.lock
Labels: Priority ‼️ High, PR :computer: DRAFT, Type 🕷 BUG FIX

#122 #KDSK-120 run_model test code 작성
  hub/tests/hub_testdata/cctv1-2021-07-17.mp4
  hub/tests/test_hub.py
Labels: Priority ❕ Low, PR 🙇‍♂️ REVIEW REQUEST, Type ⚙️ MAINTENANCE

#144 #KDSK-134 DVR 연계작업
  hub/clients/aws.py
  hub/clients/hub.py
  hub/core.py
  hub/models/utils/files.py
  hub/utils/args.py
  hub/utils/dump.py
  hub/utils/files.py
Labels: Priority ❗️ Medium, PR 🙇‍♂️ REVIEW REQUEST, Extra 🏃 SIMPLE, Type 🛠 FEATURE
